export function buildStartMessage(): string {
  return [
    '🇺🇦 OVDP Bot',
    '',
    'Я допомагаю вести облік інвестицій в українські ОВДП: покупки, очікувані виплати, порівняння з USD-сценарієм, алерти й daily FX notification.',
    '',
    'Мінімум для старту:',
    '/buy — додати покупку',
    '/portfolio — подивитися портфель',
    '/help — усі команди та приклади',
  ].join('\n');
}

export function buildHelpMessage(isAdmin: boolean): string {
  const lines = [
    '🇺🇦 OVDP Bot — трекер інвестицій в ОВДП',
    '',
    '💸 Додати покупку',
    '/buy ISIN quantity amount_uah commission_uah [purchase_date]',
    '',
    'Аргументи:',
    '• ISIN — код уже доданої облігації',
    '• quantity — кількість облігацій',
    '• amount_uah — сума всієї угоди без комісії',
    '• commission_uah — комісія в UAH',
    '• purchase_date — необовʼязково, дата покупки YYYY-MM-DD. Якщо не вказати, буде сьогодні.',
    '',
    'Приклад:',
    '/buy UA4000227045 25 24500 50 2026-04-01',
    '',
    '📊 Портфель',
    '/portfolio — показує активні покупки, їх ID, очікувані виплати, USD-сценарій, UAH-сценарій і дельти.',
    '/help portfolio — пояснює рядки в портфелі.',
    '',
    '✏️ Редагувати покупку',
    '/edit_buy purchase_id quantity amount_uah commission_uah [purchase_date]',
    'purchase_id скопіюй з /portfolio. Після редагування бот перерахує FX за датою покупки.',
    '',
    'Приклад:',
    '/edit_buy clv8k3a1 19 19500 68 2026-04-01',
    '',
    '🗑 Видалити покупку',
    '/delete_buy purchase_id',
    'Видалення мʼяке: покупка зникає з активного портфеля, але лишається в базі.',
    '',
    'Приклад:',
    '/delete_buy clv8k3a1',
    '',
    '🏁 Закрити достроково',
    '/close_buy purchase_id received_uah [close_date]',
    '/close_buy purchase_id quantity received_uah [close_date]',
    'received_uah — фактично отримана сума в UAH після продажу/закриття.',
    'quantity — необовʼязково; якщо вказати, закриється тільки частина покупки.',
    'close_date необовʼязкова; якщо не вказати, буде сьогодні.',
    '',
    'Приклад:',
    '/close_buy clv8k3a1 20100 2026-04-28',
    '/close_buy clv8k3a1 5 5300 2026-04-28',
    '',
    '🔔 Алерт',
    '/alert usd_loss_percent 3',
    'Повідомить, якщо delta_vs_usd стане нижче -3%.',
    '',
    '💱 Daily FX notification',
    '/fx_notify on [time] [currencies]',
    '/fx_notify off',
    '/fx_notify status',
    '',
    'Аргументи:',
    '• time — київський час HH:mm, за замовчуванням 09:00',
    '• currencies — USD, EUR або USD,EUR; за замовчуванням USD,EUR',
    '',
    'Приклад:',
    '/fx_notify on 09:00 USD,EUR',
    '/fx_notify on EUR',
  ];

  if (isAdmin) {
    lines.push(
      '',
      '🔐 Адмін-команди',
      '',
      '📋 Список облігацій',
      '/bonds',
      '',
      '📌 Додати облігацію',
      '/add_bond ISIN maturity_date nominal coupon_rate coupon_frequency type',
      '',
      'Аргументи:',
      '• ISIN — 12-символьний код з валідною check digit. Напр.: UA4000227045',
      '• maturity_date — дата погашення у форматі YYYY-MM-DD',
      '• nominal — номінал однієї облігації в UAH',
      '• coupon_rate — річна ставка купону у %, для zero-coupon має бути 0',
      '• coupon_frequency — none, monthly, quarterly, semi_annual, annual',
      '• type — coupon або zero_coupon',
      '',
      'Приклад:',
      '/add_bond UA4000227045 2027-05-26 1000 16.5 semi_annual coupon',
      '',
      '✏️ Редагувати облігацію',
      '/edit_bond ISIN maturity_date nominal coupon_rate coupon_frequency type',
      '',
      'Приклад:',
      '/edit_bond UA4000227045 2027-05-26 1000 17.25 semi_annual coupon',
      '',
      '⚙️ Ручний запуск daily job',
      '/run_daily_job',
      'Запускає оновлення FX, maturity handling і перевірку алертів.',
    );
  }

  return lines.join('\n');
}

export function buildPortfolioHelpMessage(): string {
  return [
    '📊 Пояснення /portfolio',
    '',
    'Очікувана виплата',
    'Сума, яку бот очікує отримати в UAH: номінал + майбутні купони. USD поруч — це перерахунок цієї суми за поточним USD/UAH.',
    '',
    'Якби купив USD',
    'Сценарій для порівняння: що було б, якби на суму покупки ти купив USD у дату покупки.',
    'Формула: total_uah / usd_rate_at_purchase',
    '',
    'Різниця до USD',
    'Наскільки ОВДП-сценарій кращий або гірший за сценарій “купив USD і тримав”.',
    'Формула: expected_total_usd - usd_hold',
    '',
    '% за весь період',
    'Це не річна ставка. Це загальна різниця до USD-сценарію від дати покупки до погашення.',
    '',
    'Результат у UAH',
    'Очікуваний прибуток або збиток у гривні.',
    'Формула: expected_total_uah - total_uah',
    '',
    'Важливо',
    'USD-результат не гарантований: він залежить від курсу USD/UAH на дату розрахунку або погашення.',
  ].join('\n');
}
